.TH "animation" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
animation \- Nome "MANOEL"
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNAME_LETTERS\fP   6"
.br
.ti -1c
.RI "#define \fBNAME_TOTAL_TICKS\fP   (\fBNAME_DURATION_MS\fP / \fBSAMPLE_PERIOD_MS\fP)"
.br
.ti -1c
.RI "#define \fBTICKS_PER_LETTER\fP   (NAME_TOTAL_TICKS / NAME_LETTERS)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Configura duração e subdivisão por letra 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
