.TH "globals" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
globals \- Variáveis de controle
.PP
 \- Variáveis utilizadas para controle interno do sistema\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Variáveis utilizadas para controle interno do sistema\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
