.TH "hardware" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hardware \- GPIO e periféricos
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWS2812_PIN\fP   7"
.br
.ti -1c
.RI "#define \fBNUM_PIXELS\fP   25"
.br
.ti -1c
.RI "#define \fBMIC_ADC_CH\fP   2"
.br
.ti -1c
.RI "#define \fBIS_RGBW\fP   false"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_RGBW   false"
Matriz RGB (false) ou RGBW (true) 
.SS "#define MIC_ADC_CH   2"
Canal ADC (GPIO 28) do microfone 
.SS "#define NUM_PIXELS   25"
LEDs na matriz 5×5 
.SS "#define WS2812_PIN   7"
GPIO para DIN da fita WS2812b 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
